title: Dazed and Confounding

theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings

paginate: 5
markdown: kramdown
highlighter: rouge